/*
 * Copyright (c) 2015 Cisco Systems, Inc. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: sfc-lisp-impl yang module local name: sfc-lisp-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Apr 27 10:32:02 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_lisp.impl;
public class SfcLispModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_lisp.impl.AbstractSfcLispModuleFactory {

}
