/*
* Generated file
*
* Generated from: yang module name: sfc-scf-ofrenderer-impl yang module local name: sfc-scf-ofrenderer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Sep 18 02:39:37 UTC 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_scf_ofrenderer.impl;
public class SfcScfOfRendererModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_scf_ofrenderer.impl.AbstractSfcScfOfRendererModuleFactory {

}
