/*
* Generated file
*
* Generated from: yang module name: service-function-provider-impl yang module local name: service-function-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jun 04 13:32:55 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.service_function_provider.impl;
public class ServiceFunctionsProviderModuleFactory extends org.opendaylight.controller.config.yang.config.service_function_provider.impl.AbstractServiceFunctionsProviderModuleFactory {

}
