/**
 * Copyright (c) 2016 Intel Ltd. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: sfc-vpp-renderer-impl yang module local name: sfc-vpp-renderer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 20 16:16:13 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_vpp_renderer.impl;
public class SfcVppRendererModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_vpp_renderer.impl.AbstractSfcVppRendererModuleFactory {

}
