/*
* Generated file
*
* Generated from: yang module name: sfc-vnfm-spi-cfg yang module local name: vnfm-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Dec 07 15:18:18 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc.vnfm.spi;
public class SfcVnfmSpiModuleFactory extends org.opendaylight.controller.config.yang.config.sfc.vnfm.spi.AbstractSfcVnfmSpiModuleFactory {

}
