/*
* Generated file
*
* Generated from: yang module name: sfc-vnfm-tacker yang module local name: sfc-vnf-tacker-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jan 08 16:10:38 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc.vnfm.tacker;
public class SfcVnfManagerProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sfc.vnfm.tacker.AbstractSfcVnfManagerProviderModuleFactory {

}
