/*
* Generated file
*
* Generated from: yang module name: sfc-sb-rest-provider-impl yang module local name: sfc-sb-rest-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 21 13:03:57 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_sb_rest_provider.impl;
public class SfcSbRestProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_sb_rest_provider.impl.AbstractSfcSbRestProviderModuleFactory {

}
