/*
 * Generated file
 *
 * Generated from: yang module name: sfcofl2-provider-impl yang module local name: sfcofl2-provider-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Thu Sep 04 17:05:35 IST 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.config.sfcofl2_provider.impl;

public class SfcOFL2ProviderModuleFactory extends
        org.opendaylight.controller.config.yang.config.sfcofl2_provider.impl.AbstractSfcOFL2ProviderModuleFactory {

}
