/*
* Generated file
*
* Generated from: yang module name: test-consumer-impl yang module local name: test-consumer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jun 17 10:46:55 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.test_consumer.impl;
public class ServiceFunctionsConsumerModuleFactory extends org.opendaylight.controller.config.yang.config.test_consumer.impl.AbstractServiceFunctionsConsumerModuleFactory {

}
