/**
 * Copyright (c) 2014 Ericsson India Global Services Pvt Ltd. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
 * Generated file
 *
 * Generated from: yang module name: sfc-l2renderer-impl yang module local name: sfc-l2renderer-impl
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Thu Sep 04 17:05:35 IST 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.config.sfc_l2renderer.impl;

public class SfcL2RendererModuleFactory extends
        org.opendaylight.controller.config.yang.config.sfc_l2renderer.impl.AbstractSfcL2RendererModuleFactory {

}
