/*
* Generated file
*
* Generated from: yang module name: sfc-netconf-impl yang module local name: sfc-netconf-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sat Mar 21 11:01:45 CDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_netconf.impl;
public class SfcNetconfModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_netconf.impl.AbstractSfcNetconfModuleFactory {

}
