/*
* Generated file
*
* Generated from: yang module name: sfc-rsp-manager-impl yang module local name: sfc-rsp-manager-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu May 05 16:10:14 CEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_rsp_manager.impl;
public class SfcRspManagerModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_rsp_manager.impl.AbstractSfcRspManagerModuleFactory {

}
