/*
* Generated file
*
* Generated from: yang module name: sfc-provider-impl yang module local name: sfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Jul 10 15:49:58 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_provider.impl;
public class SfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_provider.impl.AbstractSfcProviderModuleFactory {

}
