/**
 * Copyright (c) 2014 Ericsson India Global Services Pvt Ltd. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: sfc-ofrenderer-impl yang module local name: sfc-ofrenderer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu May 12 13:17:14 UTC 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_ofrenderer.impl;
public class SfcOfRendererModuleFactory extends
        org.opendaylight.controller.config.yang.config.sfc_ofrenderer.impl.AbstractSfcOfRendererModuleFactory {

}
