/*
* Generated file
*
* Generated from: yang module name: sfc-provider-impl yang module local name: sfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 23 16:25:00 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_provider.impl;
public class SfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_provider.impl.AbstractSfcProviderModuleFactory {

}
