/*
* Generated file
*
* Generated from: yang module name: sfc-scf-openflow-provider-impl yang module local name: sfc-scf-openflow-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Oct 25 21:22:23 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_scf_openflow_provider.impl;
public class SfcScfOfRendererModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_scf_openflow_provider.impl.AbstractSfcScfOfRendererModuleFactory {

}
