/*
* Generated file
*
* Generated from: yang module name: sfc-vnfm-impl yang module local name: sfc-vnfm-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 27 23:47:27 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sfc_vnfm.impl;
public class SfcVnfmModuleFactory extends org.opendaylight.controller.config.yang.config.sfc_vnfm.impl.AbstractSfcVnfmModuleFactory {

}
