/*
* Generated file
*
* Generated from: yang module name: ofsfc-provider-impl yang module local name: ofsfc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 29 23:13:42 IST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.ofsfc_provider.impl;
public class OfSfcProviderModuleFactory extends org.opendaylight.controller.config.yang.config.ofsfc_provider.impl.AbstractOfSfcProviderModuleFactory {

}
